// TODO: WRITE UNIT TEST FOR COLOR FUNCTIONALITIES

#include "../src/utils/color.h"
#include <gtest/gtest.h>

struct ColorTest : public testing::Test {
protected:
  ColorTest() {
    /*  CREATE COLORS THR. RGB    */
    rgbBlack = Color::fromRgb(0, 0, 0);
    rgbWhite = Color::fromRgb(255, 255, 255);
    rgbRed = Color::fromRgb(255, 0, 0);
    rgbYellow = Color::fromRgb(255, 255, 0);
    rgbGreen = Color::fromRgb(0, 255, 0);
    rgbCyan = Color::fromRgb(0, 255, 255);
    rgbBlue = Color::fromRgb(0, 0, 255);
    rgbPurple = Color::fromRgb(255, 0, 255);
    rgbRandom1 = Color::fromRgb(56, 142, 60);
    rgbRandom2 = Color::fromRgb(101, 154, 161);
    rgbRandom3 = Color::fromRgb(244, 143, 177);
    rgbRandom4 = Color::fromRgb(220, 231, 117);
    rgbRandom5 = Color::fromRgb(26, 35, 126);
    rgbRandom6 = Color::fromRgb(255, 183, 77);
    rgbRandom7 = Color::fromRgb(120, 144, 156);
    rgbRandom8 = Color::fromRgb(240, 244, 195);
    rgbRandom9 = Color::fromRgb(255, 186, 63);
    rgbRandom10 = Color::fromRgb(30, 136, 229);

    /*  CREATE COLORS THR. HEX    */
    hexBlack = Color::fromHex("#000000");
    hexWhite = Color::fromHex("#FFFFFF");
    hexRed = Color::fromHex("#FF0000");
    hexYellow = Color::fromHex("#FFFF00");
    hexGreen = Color::fromHex("#00FF00");
    hexCyan = Color::fromHex("#00FFFF");
    hexBlue = Color::fromHex("#0000FF");
    hexPurple = Color::fromHex("#FF00FF");
    hexRandom1 = Color::fromHex("#62A37D");
    hexRandom2 = Color::fromHex("#9FBF1F");
    hexRandom3 = Color::fromHex("#4F4D75");
    hexRandom4 = Color::fromHex("#4F4D75");
    hexRandom5 = Color::fromHex("#62A37D");
    hexRandom6 = Color::fromHex("#9FBF1F");
    hexRandom7 = Color::fromHex("#4F4D75");
    hexRandom8 = Color::fromHex("#62A37D");
    hexRandom9 = Color::fromHex("#9FBF1F");
    hexRandom10 = Color::fromHex("#4F4D75");

    /*  CREATE COLORS THR. HSL    */
    hslBlack = Color::fromHsl(0, 0, 0);
    hslWhite = Color::fromHsl(0, 0, 100);
    hslRed = Color::fromHsl(0, 100, 50);
    hslYellow = Color::fromHsl(60, 100, 50);
    hslGreen = Color::fromHsl(120, 100, 50);
    hslCyan = Color::fromHsl(180, 100, 50);
    hslBlue = Color::fromHsl(240, 100, 50);
    hslPurple = Color::fromHsl(300, 100, 50);
    hslRandom1 = Color::fromHsl(123, 43, 39);
    hslRandom2 = Color::fromHsl(187, 24, 51);
    hslRandom3 = Color::fromHsl(340, 82, 76);
    hslRandom4 = Color::fromHsl(66, 70, 68);
    hslRandom5 = Color::fromHsl(235, 66, 30);
    hslRandom6 = Color::fromHsl(36, 100, 65);
    hslRandom7 = Color::fromHsl(200, 15, 54);
    hslRandom8 = Color::fromHsl(65, 69, 86);
    hslRandom9 = Color::fromHsl(38, 100, 62.4);
    hslRandom10 = Color::fromHsl(208, 79, 51);

    /*  CREATE COLORS THR. HSV    */
    hsvBlack = Color::fromHsv(0, 0, 0);
    hsvWhite = Color::fromHsv(0, 0, 100);
    hsvRed = Color::fromHsv(0, 100, 100);
    hsvYellow = Color::fromHsv(60, 100, 100);
    hsvGreen = Color::fromHsv(120, 100, 100);
    hsvCyan = Color::fromHsv(180, 100, 100);
    hsvBlue = Color::fromHsv(240, 100, 100);
    hsvPurple = Color::fromHsv(300, 100, 100);
    hsvRandom1 = Color::fromHsv(123, 61, 56);
    hsvRandom2 = Color::fromHsv(187, 37, 63);
    hsvRandom3 = Color::fromHsv(340, 41, 96);
    hsvRandom4 = Color::fromHsv(66, 49, 91);
    hsvRandom5 = Color::fromHsv(235, 79, 49);
    hsvRandom6 = Color::fromHsv(36, 70, 100);
    hsvRandom7 = Color::fromHsv(200, 23, 61);
    hsvRandom8 = Color::fromHsv(65, 20, 96);
    hsvRandom9 = Color::fromHsv(38, 75, 100);
    hsvRandom10 = Color::fromHsv(208, 87, 90);
  }
  ~ColorTest() override = default;
  void SetUp() override {}
  void TearDown() override {}

  Color rgbBlack;
  Color rgbWhite;
  Color rgbRed;
  Color rgbYellow;
  Color rgbGreen;
  Color rgbCyan;
  Color rgbBlue;
  Color rgbPurple;
  Color rgbRandom1;
  Color rgbRandom2;
  Color rgbRandom3;
  Color rgbRandom4;
  Color rgbRandom5;
  Color rgbRandom6;
  Color rgbRandom7;
  Color rgbRandom8;
  Color rgbRandom9;
  Color rgbRandom10;

  Color hexBlack;
  Color hexWhite;
  Color hexRed;
  Color hexYellow;
  Color hexGreen;
  Color hexCyan;
  Color hexBlue;
  Color hexPurple;
  Color hexRandom1;
  Color hexRandom2;
  Color hexRandom3;
  Color hexRandom4;
  Color hexRandom5;
  Color hexRandom6;
  Color hexRandom7;
  Color hexRandom8;
  Color hexRandom9;
  Color hexRandom10;

  Color hslBlack;
  Color hslWhite;
  Color hslRed;
  Color hslYellow;
  Color hslGreen;
  Color hslCyan;
  Color hslBlue;
  Color hslPurple;
  Color hslRandom1;
  Color hslRandom2;
  Color hslRandom3;
  Color hslRandom4;
  Color hslRandom5;
  Color hslRandom6;
  Color hslRandom7;
  Color hslRandom8;
  Color hslRandom9;
  Color hslRandom10;

  Color hsvBlack;
  Color hsvWhite;
  Color hsvRed;
  Color hsvYellow;
  Color hsvGreen;
  Color hsvCyan;
  Color hsvBlue;
  Color hsvPurple;
  Color hsvRandom1;
  Color hsvRandom2;
  Color hsvRandom3;
  Color hsvRandom4;
  Color hsvRandom5;
  Color hsvRandom6;
  Color hsvRandom7;
  Color hsvRandom8;
  Color hsvRandom9;
  Color hsvRandom10;
};

TEST_F(ColorTest, GetRed) {
  EXPECT_NEAR(rgbBlack.getRed(), 0, 1);
  EXPECT_NEAR(rgbWhite.getRed(), 255, 1);
  EXPECT_NEAR(rgbRed.getRed(), 255, 1);
  EXPECT_NEAR(rgbYellow.getRed(), 255, 1);
  EXPECT_NEAR(rgbGreen.getRed(), 0, 1);
  EXPECT_NEAR(rgbCyan.getRed(), 0, 1);
  EXPECT_NEAR(rgbBlue.getRed(), 0, 1);
  EXPECT_NEAR(rgbPurple.getRed(), 255, 1);
  EXPECT_NEAR(rgbRandom1.getRed(), 56, 1);
  EXPECT_NEAR(rgbRandom2.getRed(), 101, 1);
  EXPECT_NEAR(rgbRandom3.getRed(), 244, 1);
  EXPECT_NEAR(rgbRandom4.getRed(), 220, 1);
  EXPECT_NEAR(rgbRandom5.getRed(), 26, 1);
  EXPECT_NEAR(rgbRandom6.getRed(), 255, 1);
  EXPECT_NEAR(rgbRandom7.getRed(), 120, 1);
  EXPECT_NEAR(rgbRandom8.getRed(), 240, 1);
  EXPECT_NEAR(rgbRandom9.getRed(), 255, 1);
  EXPECT_NEAR(rgbRandom10.getRed(), 30, 1);

  // EXPECT_NEAR(hexBlack.getRed(),    0,   1);
  // EXPECT_NEAR(hexWhite.getRed(),    255, 1);
  // EXPECT_NEAR(hexRed.getRed(),      255, 1);
  // EXPECT_NEAR(hexYellow.getRed(),   255, 1);
  // EXPECT_NEAR(hexGreen.getRed(),    0,   1);
  // EXPECT_NEAR(hexCyan.getRed(),     0,   1);
  // EXPECT_NEAR(hexBlue.getRed(),     0,   1);
  // EXPECT_NEAR(hexPurple.getRed(),   255, 1);
  // EXPECT_NEAR(hexRandom1.getRed(),  56,  1);
  // EXPECT_NEAR(hexRandom2.getRed(),  101, 1);
  // EXPECT_NEAR(hexRandom3.getRed(),  244, 1);
  // EXPECT_NEAR(hexRandom4.getRed(),  220, 1);
  // EXPECT_NEAR(hexRandom5.getRed(),  26,  1);
  // EXPECT_NEAR(hexRandom6.getRed(),  255, 1);
  // EXPECT_NEAR(hexRandom7.getRed(),  120, 1);
  // EXPECT_NEAR(hexRandom8.getRed(),  240, 1);
  // EXPECT_NEAR(hexRandom9.getRed(),  255, 1);
  // EXPECT_NEAR(hexRandom10.getRed(), 30,  1);

  EXPECT_NEAR(hslBlack.getRed(), 0, 1);
  EXPECT_NEAR(hslWhite.getRed(), 255, 1);
  EXPECT_NEAR(hslRed.getRed(), 255, 1);
  EXPECT_NEAR(hslYellow.getRed(), 255, 1);
  EXPECT_NEAR(hslGreen.getRed(), 0, 1);
  EXPECT_NEAR(hslCyan.getRed(), 0, 1);
  EXPECT_NEAR(hslBlue.getRed(), 0, 1);
  EXPECT_NEAR(hslPurple.getRed(), 255, 1);
  EXPECT_NEAR(hslRandom1.getRed(), 56, 1);
  EXPECT_NEAR(hslRandom2.getRed(), 101, 1);
  EXPECT_NEAR(hslRandom3.getRed(), 244, 1);
  EXPECT_NEAR(hslRandom4.getRed(), 220, 1);
  EXPECT_NEAR(hslRandom5.getRed(), 26, 1);
  EXPECT_NEAR(hslRandom6.getRed(), 255, 1);
  EXPECT_NEAR(hslRandom7.getRed(), 120, 1);
  EXPECT_NEAR(hslRandom8.getRed(), 240, 1);
  EXPECT_NEAR(hslRandom9.getRed(), 255, 1);
  EXPECT_NEAR(hslRandom10.getRed(), 30, 1);

  EXPECT_NEAR(hsvBlack.getRed(), 0, 1);
  EXPECT_NEAR(hsvWhite.getRed(), 255, 1);
  EXPECT_NEAR(hsvRed.getRed(), 255, 1);
  EXPECT_NEAR(hsvYellow.getRed(), 255, 1);
  EXPECT_NEAR(hsvGreen.getRed(), 0, 1);
  EXPECT_NEAR(hsvCyan.getRed(), 0, 1);
  EXPECT_NEAR(hsvBlue.getRed(), 0, 1);
  EXPECT_NEAR(hsvPurple.getRed(), 255, 1);
  EXPECT_NEAR(hsvRandom1.getRed(), 56, 1);
  EXPECT_NEAR(hsvRandom2.getRed(), 101, 1);
  EXPECT_NEAR(hsvRandom3.getRed(), 244, 1);
  EXPECT_NEAR(hsvRandom4.getRed(), 220, 1);
  EXPECT_NEAR(hsvRandom5.getRed(), 26, 1);
  EXPECT_NEAR(hsvRandom6.getRed(), 255, 1);
  EXPECT_NEAR(hsvRandom7.getRed(), 120, 1);
  EXPECT_NEAR(hsvRandom8.getRed(), 240, 1);
  EXPECT_NEAR(hsvRandom9.getRed(), 255, 1);
  EXPECT_NEAR(hsvRandom10.getRed(), 30, 1);
}

TEST_F(ColorTest, GetGreen) {
  EXPECT_NEAR(rgbBlack.getGreen(), 0, 1);
  EXPECT_NEAR(rgbWhite.getGreen(), 255, 1);
  EXPECT_NEAR(rgbRed.getGreen(), 0, 1);
  EXPECT_NEAR(rgbYellow.getGreen(), 255, 1);
  EXPECT_NEAR(rgbGreen.getGreen(), 255, 1);
  EXPECT_NEAR(rgbCyan.getGreen(), 255, 1);
  EXPECT_NEAR(rgbBlue.getGreen(), 0, 1);
  EXPECT_NEAR(rgbPurple.getGreen(), 0, 1);
  EXPECT_NEAR(rgbRandom1.getGreen(), 142, 1);
  EXPECT_NEAR(rgbRandom2.getGreen(), 154, 1);
  EXPECT_NEAR(rgbRandom3.getGreen(), 143, 1);
  EXPECT_NEAR(rgbRandom4.getGreen(), 231, 1);
  EXPECT_NEAR(rgbRandom5.getGreen(), 35, 1);
  EXPECT_NEAR(rgbRandom6.getGreen(), 183, 1);
  EXPECT_NEAR(rgbRandom7.getGreen(), 144, 1);
  EXPECT_NEAR(rgbRandom8.getGreen(), 244, 1);
  EXPECT_NEAR(rgbRandom9.getGreen(), 186, 1);
  EXPECT_NEAR(rgbRandom10.getGreen(), 136, 1);

  // EXPECT_NEAR(hexBlack.getGreen(),    0,   1);
  // EXPECT_NEAR(hexWhite.getGreen(),    255, 1);
  // EXPECT_NEAR(hexRed.getGreen(),      255, 1);
  // EXPECT_NEAR(hexYellow.getGreen(),   255, 1);
  // EXPECT_NEAR(hexGreen.getGreen(),    0,   1);
  // EXPECT_NEAR(hexCyan.getGreen(),     0,   1);
  // EXPECT_NEAR(hexBlue.getGreen(),     0,   1);
  // EXPECT_NEAR(hexPurple.getGreen(),   255, 1);
  // EXPECT_NEAR(hexRandom1.getGreen(),  56,  1);
  // EXPECT_NEAR(hexRandom2.getGreen(),  101, 1);
  // EXPECT_NEAR(hexRandom3.getGreen(),  244, 1);
  // EXPECT_NEAR(hexRandom4.getGreen(),  220, 1);
  // EXPECT_NEAR(hexRandom5.getGreen(),  26,  1);
  // EXPECT_NEAR(hexRandom6.getGreen(),  255, 1);
  // EXPECT_NEAR(hexRandom7.getGreen(),  120, 1);
  // EXPECT_NEAR(hexRandom8.getGreen(),  240, 1);
  // EXPECT_NEAR(hexRandom9.getGreen(),  255, 1);
  // EXPECT_NEAR(hexRandom10.getGreen(), 30,  1);

  EXPECT_NEAR(hslBlack.getGreen(), 0, 1);
  EXPECT_NEAR(hslWhite.getGreen(), 255, 1);
  EXPECT_NEAR(hslRed.getGreen(), 0, 1);
  EXPECT_NEAR(hslYellow.getGreen(), 255, 1);
  EXPECT_NEAR(hslGreen.getGreen(), 255, 1);
  EXPECT_NEAR(hslCyan.getGreen(), 255, 1);
  EXPECT_NEAR(hslBlue.getGreen(), 0, 1);
  EXPECT_NEAR(hslPurple.getGreen(), 0, 1);
  EXPECT_NEAR(hslRandom1.getGreen(), 142, 1);
  EXPECT_NEAR(hslRandom2.getGreen(), 154, 1);
  EXPECT_NEAR(hslRandom3.getGreen(), 143, 1);
  EXPECT_NEAR(hslRandom4.getGreen(), 231, 1);
  EXPECT_NEAR(hslRandom5.getGreen(), 35, 1);
  EXPECT_NEAR(hslRandom6.getGreen(), 183, 1);
  EXPECT_NEAR(hslRandom7.getGreen(), 144, 1);
  EXPECT_NEAR(hslRandom8.getGreen(), 244, 1);
  EXPECT_NEAR(hslRandom9.getGreen(), 186, 1);
  EXPECT_NEAR(hslRandom10.getGreen(), 136, 1);

  EXPECT_NEAR(hsvBlack.getGreen(), 0, 1);
  EXPECT_NEAR(hsvWhite.getGreen(), 255, 1);
  EXPECT_NEAR(hsvRed.getGreen(), 0, 1);
  EXPECT_NEAR(hsvYellow.getGreen(), 255, 1);
  EXPECT_NEAR(hsvGreen.getGreen(), 255, 1);
  EXPECT_NEAR(hsvCyan.getGreen(), 255, 1);
  EXPECT_NEAR(hsvBlue.getGreen(), 0, 1);
  EXPECT_NEAR(hsvPurple.getGreen(), 0, 1);
  EXPECT_NEAR(hsvRandom1.getGreen(), 142, 1);
  EXPECT_NEAR(hsvRandom2.getGreen(), 154, 1);
  EXPECT_NEAR(hsvRandom3.getGreen(), 143, 1);
  EXPECT_NEAR(hsvRandom4.getGreen(), 231, 1);
  EXPECT_NEAR(hsvRandom5.getGreen(), 35, 1);
  EXPECT_NEAR(hsvRandom6.getGreen(), 183, 1);
  EXPECT_NEAR(hsvRandom7.getGreen(), 144, 1);
  EXPECT_NEAR(hsvRandom8.getGreen(), 244, 1);
  EXPECT_NEAR(hsvRandom9.getGreen(), 186, 1);
  EXPECT_NEAR(hsvRandom10.getGreen(), 136, 1);
}

TEST_F(ColorTest, GetBlue) {
  EXPECT_NEAR(rgbBlack.getBlue(), 0, 1);
  EXPECT_NEAR(rgbWhite.getBlue(), 255, 1);
  EXPECT_NEAR(rgbRed.getBlue(), 0, 1);
  EXPECT_NEAR(rgbYellow.getBlue(), 0, 1);
  EXPECT_NEAR(rgbGreen.getBlue(), 0, 1);
  EXPECT_NEAR(rgbCyan.getBlue(), 255, 1);
  EXPECT_NEAR(rgbBlue.getBlue(), 255, 1);
  EXPECT_NEAR(rgbPurple.getBlue(), 255, 1);
  EXPECT_NEAR(rgbRandom1.getBlue(), 60, 1);
  EXPECT_NEAR(rgbRandom2.getBlue(), 161, 1);
  EXPECT_NEAR(rgbRandom3.getBlue(), 177, 1);
  EXPECT_NEAR(rgbRandom4.getBlue(), 117, 1);
  EXPECT_NEAR(rgbRandom5.getBlue(), 126, 1);
  EXPECT_NEAR(rgbRandom6.getBlue(), 77, 1);
  EXPECT_NEAR(rgbRandom7.getBlue(), 156, 1);
  EXPECT_NEAR(rgbRandom8.getBlue(), 195, 1);
  EXPECT_NEAR(rgbRandom9.getBlue(), 63, 1);
  EXPECT_NEAR(rgbRandom10.getBlue(), 229, 1);

  //  EXPECT_NEAR(hexBlack.getBlue(), 0, 1);
  //  EXPECT_NEAR(hexWhite.getBlue(), 255, 1);
  //  EXPECT_NEAR(hexRed.getBlue(), 0, 1);
  //  EXPECT_NEAR(hexYellow.getBlue(), 0, 1);
  //  EXPECT_NEAR(hexGreen.getBlue(), 0, 1);
  //  EXPECT_NEAR(hexCyan.getBlue(), 255, 1);
  //  EXPECT_NEAR(hexBlue.getBlue(), 255, 1);
  //  EXPECT_NEAR(hexPurple.getBlue(), 255, 1);
  //  EXPECT_NEAR(hexRandom1.getBlue(), 60, 1);
  //  EXPECT_NEAR(hexRandom2.getBlue(), 161, 1);
  //  EXPECT_NEAR(hexRandom3.getBlue(), 177, 1);
  //  EXPECT_NEAR(hexRandom4.getBlue(), 117, 1);
  //  EXPECT_NEAR(hexRandom5.getBlue(), 126, 1);
  //  EXPECT_NEAR(hexRandom6.getBlue(), 77, 1);
  //  EXPECT_NEAR(hexRandom7.getBlue(), 156, 1);
  //  EXPECT_NEAR(hexRandom8.getBlue(), 195, 1);
  //  EXPECT_NEAR(hexRandom9.getBlue(), 63, 1);
  //  EXPECT_NEAR(hexRandom10.getBlue(), 229, 1);

  EXPECT_NEAR(hslBlack.getBlue(), 0, 1);
  EXPECT_NEAR(hslWhite.getBlue(), 255, 1);
  EXPECT_NEAR(hslRed.getBlue(), 0, 1);
  EXPECT_NEAR(hslYellow.getBlue(), 0, 1);
  EXPECT_NEAR(hslGreen.getBlue(), 0, 1);
  EXPECT_NEAR(hslCyan.getBlue(), 255, 1);
  EXPECT_NEAR(hslBlue.getBlue(), 255, 1);
  EXPECT_NEAR(hslPurple.getBlue(), 255, 1);
  EXPECT_NEAR(hslRandom1.getBlue(), 60, 1);
  EXPECT_NEAR(hslRandom2.getBlue(), 161, 1);
  EXPECT_NEAR(hslRandom3.getBlue(), 177, 1);
  EXPECT_NEAR(hslRandom4.getBlue(), 117, 1);
  EXPECT_NEAR(hslRandom5.getBlue(), 126, 1);
  EXPECT_NEAR(hslRandom6.getBlue(), 77, 1);
  EXPECT_NEAR(hslRandom7.getBlue(), 156, 1);
  EXPECT_NEAR(hslRandom8.getBlue(), 195, 1);
  EXPECT_NEAR(hslRandom9.getBlue(), 63, 1);
  EXPECT_NEAR(hslRandom10.getBlue(), 229, 1);

  EXPECT_NEAR(hsvBlack.getBlue(), 0, 1);
  EXPECT_NEAR(hsvWhite.getBlue(), 255, 1);
  EXPECT_NEAR(hsvRed.getBlue(), 0, 1);
  EXPECT_NEAR(hsvYellow.getBlue(), 0, 1);
  EXPECT_NEAR(hsvGreen.getBlue(), 0, 1);
  EXPECT_NEAR(hsvCyan.getBlue(), 255, 1);
  EXPECT_NEAR(hsvBlue.getBlue(), 255, 1);
  EXPECT_NEAR(hsvPurple.getBlue(), 255, 1);
  EXPECT_NEAR(hsvRandom1.getBlue(), 60, 1);
  EXPECT_NEAR(hsvRandom2.getBlue(), 161, 1);
  EXPECT_NEAR(hsvRandom3.getBlue(), 177, 1);
  EXPECT_NEAR(hsvRandom4.getBlue(), 117, 1);
  EXPECT_NEAR(hsvRandom5.getBlue(), 126, 1);
  EXPECT_NEAR(hsvRandom6.getBlue(), 77, 1);
  EXPECT_NEAR(hsvRandom7.getBlue(), 156, 1);
  EXPECT_NEAR(hsvRandom8.getBlue(), 195, 1);
  EXPECT_NEAR(hsvRandom9.getBlue(), 63, 1);
  EXPECT_NEAR(hsvRandom10.getBlue(), 229, 1);
}

TEST_F(ColorTest, GetHue) {
  EXPECT_NEAR(rgbBlack.getHue(), 0, 1);
  EXPECT_NEAR(rgbWhite.getHue(), 0, 1);
  EXPECT_NEAR(rgbRed.getHue(), 0, 1);
  EXPECT_NEAR(rgbYellow.getHue(), 60, 1);
  EXPECT_NEAR(rgbGreen.getHue(), 120, 1);
  EXPECT_NEAR(rgbCyan.getHue(), 180, 1);
  EXPECT_NEAR(rgbBlue.getHue(), 240, 1);
  EXPECT_NEAR(rgbPurple.getHue(), 300, 1);
  EXPECT_NEAR(rgbRandom1.getHue(), 123, 1);
  EXPECT_NEAR(rgbRandom2.getHue(), 187, 1);
  EXPECT_NEAR(rgbRandom3.getHue(), 340, 1);
  EXPECT_NEAR(rgbRandom4.getHue(), 66, 1);
  EXPECT_NEAR(rgbRandom5.getHue(), 235, 1);
  EXPECT_NEAR(rgbRandom6.getHue(), 36, 1);
  EXPECT_NEAR(rgbRandom7.getHue(), 200, 1);
  EXPECT_NEAR(rgbRandom8.getHue(), 65, 1);
  EXPECT_NEAR(rgbRandom9.getHue(), 38, 1);
  EXPECT_NEAR(rgbRandom10.getHue(), 208, 1);

  //  EXPECT_NEAR(hexBlack.getHue(),     0,  1);
  //  EXPECT_NEAR(hexWhite.getHue(),     0,  1);
  //  EXPECT_NEAR(hexRed.getHue(),       0,  1);
  //  EXPECT_NEAR(hexYellow.getHue(),    60, 1);
  //  EXPECT_NEAR(hexGreen.getHue(),     120,1);
  //  EXPECT_NEAR(hexCyan.getHue(),      180,1);
  //  EXPECT_NEAR(hexBlue.getHue(),      240,1);
  //  EXPECT_NEAR(hexPurple.getHue(),    300,1);
  //  EXPECT_NEAR(hexRandom1.getHue(),   123,1);
  //  EXPECT_NEAR(hexRandom2.getHue(),   187,1);
  //  EXPECT_NEAR(hexRandom3.getHue(),   340,1);
  //  EXPECT_NEAR(hexRandom4.getHue(),   66, 1);
  //  EXPECT_NEAR(hexRandom5.getHue(),   235,1);
  //  EXPECT_NEAR(hexRandom6.getHue(),   36, 1);
  //  EXPECT_NEAR(hexRandom7.getHue(),   200,1);
  //  EXPECT_NEAR(hexRandom8.getHue(),   65, 1);
  //  EXPECT_NEAR(hexRandom9.getHue(),   38, 1);
  //  EXPECT_NEAR(hexRandom10.getHue(),  208,1);

  EXPECT_NEAR(hslBlack.getHue(), 0, 1);
  EXPECT_NEAR(hslWhite.getHue(), 0, 1);
  EXPECT_NEAR(hslRed.getHue(), 0, 1);
  EXPECT_NEAR(hslYellow.getHue(), 60, 1);
  EXPECT_NEAR(hslGreen.getHue(), 120, 1);
  EXPECT_NEAR(hslCyan.getHue(), 180, 1);
  EXPECT_NEAR(hslBlue.getHue(), 240, 1);
  EXPECT_NEAR(hslPurple.getHue(), 300, 1);
  EXPECT_NEAR(hslRandom1.getHue(), 123, 1);
  EXPECT_NEAR(hslRandom2.getHue(), 187, 1);
  EXPECT_NEAR(hslRandom3.getHue(), 340, 1);
  EXPECT_NEAR(hslRandom4.getHue(), 66, 1);
  EXPECT_NEAR(hslRandom5.getHue(), 235, 1);
  EXPECT_NEAR(hslRandom6.getHue(), 36, 1);
  EXPECT_NEAR(hslRandom7.getHue(), 200, 1);
  EXPECT_NEAR(hslRandom8.getHue(), 65, 1);
  EXPECT_NEAR(hslRandom9.getHue(), 38, 1);
  EXPECT_NEAR(hslRandom10.getHue(), 208, 1);

  EXPECT_NEAR(hsvBlack.getHue(), 0, 1);
  EXPECT_NEAR(hsvWhite.getHue(), 0, 1);
  EXPECT_NEAR(hsvRed.getHue(), 0, 1);
  EXPECT_NEAR(hsvYellow.getHue(), 60, 1);
  EXPECT_NEAR(hsvGreen.getHue(), 120, 1);
  EXPECT_NEAR(hsvCyan.getHue(), 180, 1);
  EXPECT_NEAR(hsvBlue.getHue(), 240, 1);
  EXPECT_NEAR(hsvPurple.getHue(), 300, 1);
  EXPECT_NEAR(hsvRandom1.getHue(), 123, 1);
  EXPECT_NEAR(hsvRandom2.getHue(), 187, 1);
  EXPECT_NEAR(hsvRandom3.getHue(), 340, 1);
  EXPECT_NEAR(hsvRandom4.getHue(), 66, 1);
  EXPECT_NEAR(hsvRandom5.getHue(), 235, 1);
  EXPECT_NEAR(hsvRandom6.getHue(), 36, 1);
  EXPECT_NEAR(hsvRandom7.getHue(), 200, 1);
  EXPECT_NEAR(hsvRandom8.getHue(), 65, 1);
  EXPECT_NEAR(hsvRandom9.getHue(), 38, 1);
  EXPECT_NEAR(hsvRandom10.getHue(), 208, 1);
}

TEST_F(ColorTest, GetHSLSaturation) {
  EXPECT_NEAR(rgbBlack.getHSLSaturation(), 0, 1);
  EXPECT_NEAR(rgbWhite.getHSLSaturation(), 0, 1);
  EXPECT_NEAR(rgbRed.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(rgbYellow.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(rgbGreen.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(rgbCyan.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(rgbBlue.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(rgbPurple.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(rgbRandom1.getHSLSaturation(), 43, 1);
  EXPECT_NEAR(rgbRandom2.getHSLSaturation(), 24, 1);
  EXPECT_NEAR(rgbRandom3.getHSLSaturation(), 82, 1);
  EXPECT_NEAR(rgbRandom4.getHSLSaturation(), 70, 1);
  EXPECT_NEAR(rgbRandom5.getHSLSaturation(), 66, 1);
  EXPECT_NEAR(rgbRandom6.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(rgbRandom7.getHSLSaturation(), 15, 1);
  EXPECT_NEAR(rgbRandom8.getHSLSaturation(), 69, 1);
  EXPECT_NEAR(rgbRandom9.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(rgbRandom10.getHSLSaturation(), 79, 1);

  //  EXPECT_NEAR(hexBlack.getHSLSaturation(),  0,    1);
  //  EXPECT_NEAR(hexWhite.getHSLSaturation(),  0,    1);
  //  EXPECT_NEAR(hexRed.getHSLSaturation(),    100,  1);
  //  EXPECT_NEAR(hexYellow.getHSLSaturation(), 100,  1);
  //  EXPECT_NEAR(hexGreen.getHSLSaturation(),  100,  1);
  //  EXPECT_NEAR(hexCyan.getHSLSaturation(),   100,  1);
  //  EXPECT_NEAR(hexBlue.getHSLSaturation(),   100,  1);
  //  EXPECT_NEAR(hexPurple.getHSLSaturation(), 100,  1);
  //  EXPECT_NEAR(hexRandom1.getHSLSaturation() ,43,   1);
  //  EXPECT_NEAR(hexRandom2.getHSLSaturation() ,24,   1);
  //  EXPECT_NEAR(hexRandom3.getHSLSaturation() ,82,   1);
  //  EXPECT_NEAR(hexRandom4.getHSLSaturation() ,70,   1);
  //  EXPECT_NEAR(hexRandom5.getHSLSaturation() ,66,   1);
  //  EXPECT_NEAR(hexRandom6.getHSLSaturation() ,100,  1);
  //  EXPECT_NEAR(hexRandom7.getHSLSaturation() ,15,   1);
  //  EXPECT_NEAR(hexRandom8.getHSLSaturation() ,69,   1);
  //  EXPECT_NEAR(hexRandom9.getHSLSaturation() ,100,  1);
  //  EXPECT_NEAR(hexRandom10.getHSLSaturation(), 79,  1);

  EXPECT_NEAR(hslBlack.getHSLSaturation(), 0, 1);
  EXPECT_NEAR(hslWhite.getHSLSaturation(), 0, 1);
  EXPECT_NEAR(hslRed.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hslYellow.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hslGreen.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hslCyan.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hslBlue.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hslPurple.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hslRandom1.getHSLSaturation(), 43, 1);
  EXPECT_NEAR(hslRandom2.getHSLSaturation(), 24, 1);
  EXPECT_NEAR(hslRandom3.getHSLSaturation(), 82, 1);
  EXPECT_NEAR(hslRandom4.getHSLSaturation(), 70, 1);
  EXPECT_NEAR(hslRandom5.getHSLSaturation(), 66, 1);
  EXPECT_NEAR(hslRandom6.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hslRandom7.getHSLSaturation(), 15, 1);
  EXPECT_NEAR(hslRandom8.getHSLSaturation(), 69, 1);
  EXPECT_NEAR(hslRandom9.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hslRandom10.getHSLSaturation(), 79, 1);

  EXPECT_NEAR(hsvBlack.getHSLSaturation(), 0, 1);
  EXPECT_NEAR(hsvWhite.getHSLSaturation(), 0, 1);
  EXPECT_NEAR(hsvRed.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hsvYellow.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hsvGreen.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hsvCyan.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hsvBlue.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hsvPurple.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hsvRandom1.getHSLSaturation(), 43, 1);
  EXPECT_NEAR(hsvRandom2.getHSLSaturation(), 24, 1);
  EXPECT_NEAR(hsvRandom3.getHSLSaturation(), 82, 1);
  EXPECT_NEAR(hsvRandom4.getHSLSaturation(), 70, 1);
  EXPECT_NEAR(hsvRandom5.getHSLSaturation(), 66, 1);
  EXPECT_NEAR(hsvRandom6.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hsvRandom7.getHSLSaturation(), 15, 1);
  EXPECT_NEAR(hsvRandom8.getHSLSaturation(), 70, 1);
  EXPECT_NEAR(hsvRandom9.getHSLSaturation(), 100, 1);
  EXPECT_NEAR(hsvRandom10.getHSLSaturation(), 79, 1);
}

TEST_F(ColorTest, GetHSVSaturation) {
  EXPECT_NEAR(rgbBlack.getHSVSaturation(), 0, 1);
  EXPECT_NEAR(rgbWhite.getHSVSaturation(), 0, 1);
  EXPECT_NEAR(rgbRed.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(rgbYellow.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(rgbGreen.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(rgbCyan.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(rgbBlue.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(rgbPurple.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(rgbRandom1.getHSVSaturation(), 61, 1);
  EXPECT_NEAR(rgbRandom2.getHSVSaturation(), 37, 1);
  EXPECT_NEAR(rgbRandom3.getHSVSaturation(), 41, 1);
  EXPECT_NEAR(rgbRandom4.getHSVSaturation(), 49, 1);
  EXPECT_NEAR(rgbRandom5.getHSVSaturation(), 79, 1);
  EXPECT_NEAR(rgbRandom6.getHSVSaturation(), 70, 1);
  EXPECT_NEAR(rgbRandom7.getHSVSaturation(), 23, 1);
  EXPECT_NEAR(rgbRandom8.getHSVSaturation(), 20, 1);
  EXPECT_NEAR(rgbRandom9.getHSVSaturation(), 75, 1);
  EXPECT_NEAR(rgbRandom10.getHSVSaturation(), 87, 1);

  //  EXPECT_NEAR(hexBlack.getHSVSaturation(),  0,     1);
  //  EXPECT_NEAR(hexWhite.getHSVSaturation(),  0,     1);
  //  EXPECT_NEAR(hexRed.getHSVSaturation(),    100,   1);
  //  EXPECT_NEAR(hexYellow.getHSVSaturation(), 100,   1);
  //  EXPECT_NEAR(hexGreen.getHSVSaturation(),  100,   1);
  //  EXPECT_NEAR(hexCyan.getHSVSaturation(),   100,   1);
  //  EXPECT_NEAR(hexBlue.getHSVSaturation(),   100,   1);
  //  EXPECT_NEAR(hexPurple.getHSVSaturation(), 100,   1);
  //  EXPECT_NEAR(hexRandom1.getHSVSaturation(),61,    1);
  //  EXPECT_NEAR(hexRandom2.getHSVSaturation(),37,    1);
  //  EXPECT_NEAR(hexRandom3.getHSVSaturation(),41,    1);
  //  EXPECT_NEAR(hexRandom4.getHSVSaturation(),49,    1);
  //  EXPECT_NEAR(hexRandom5.getHSVSaturation(),79,    1);
  //  EXPECT_NEAR(hexRandom6.getHSVSaturation(),70,    1);
  //  EXPECT_NEAR(hexRandom7.getHSVSaturation(),23,    1);
  //  EXPECT_NEAR(hexRandom8.getHSVSaturation(),20,    1);
  //  EXPECT_NEAR(hexRandom9.getHSVSaturation(),75,    1);
  //  EXPECT_NEAR(hexRandom10.getHSVSaturation(),87,  1);

  EXPECT_NEAR(hslBlack.getHSVSaturation(), 0, 1);
  EXPECT_NEAR(hslWhite.getHSVSaturation(), 0, 1);
  EXPECT_NEAR(hslRed.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hslYellow.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hslGreen.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hslCyan.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hslBlue.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hslPurple.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hslRandom1.getHSVSaturation(), 61, 1);
  EXPECT_NEAR(hslRandom2.getHSVSaturation(), 37, 1);
  EXPECT_NEAR(hslRandom3.getHSVSaturation(), 41, 1);
  EXPECT_NEAR(hslRandom4.getHSVSaturation(), 49, 1);
  EXPECT_NEAR(hslRandom5.getHSVSaturation(), 79, 1);
  EXPECT_NEAR(hslRandom6.getHSVSaturation(), 70, 1);
  EXPECT_NEAR(hslRandom7.getHSVSaturation(), 23, 1);
  EXPECT_NEAR(hslRandom8.getHSVSaturation(), 20, 1);
  EXPECT_NEAR(hslRandom9.getHSVSaturation(), 75, 1);
  EXPECT_NEAR(hslRandom10.getHSVSaturation(), 87, 1);

  EXPECT_NEAR(hsvBlack.getHSVSaturation(), 0, 1);
  EXPECT_NEAR(hsvWhite.getHSVSaturation(), 0, 1);
  EXPECT_NEAR(hsvRed.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hsvYellow.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hsvGreen.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hsvCyan.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hsvBlue.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hsvPurple.getHSVSaturation(), 100, 1);
  EXPECT_NEAR(hsvRandom1.getHSVSaturation(), 61, 1);
  EXPECT_NEAR(hsvRandom2.getHSVSaturation(), 37, 1);
  EXPECT_NEAR(hsvRandom3.getHSVSaturation(), 41, 1);
  EXPECT_NEAR(hsvRandom4.getHSVSaturation(), 49, 1);
  EXPECT_NEAR(hsvRandom5.getHSVSaturation(), 79, 1);
  EXPECT_NEAR(hsvRandom6.getHSVSaturation(), 70, 1);
  EXPECT_NEAR(hsvRandom7.getHSVSaturation(), 23, 1);
  EXPECT_NEAR(hsvRandom8.getHSVSaturation(), 20, 1);
  EXPECT_NEAR(hsvRandom9.getHSVSaturation(), 75, 1);
  EXPECT_NEAR(hsvRandom10.getHSVSaturation(), 87, 1);
}

TEST_F(ColorTest, GetValue) {
  EXPECT_NEAR(rgbBlack.getValue(), 0, 1);
  EXPECT_NEAR(rgbWhite.getValue(), 100, 1);
  EXPECT_NEAR(rgbRed.getValue(), 100, 1);
  EXPECT_NEAR(rgbYellow.getValue(), 100, 1);
  EXPECT_NEAR(rgbGreen.getValue(), 100, 1);
  EXPECT_NEAR(rgbCyan.getValue(), 100, 1);
  EXPECT_NEAR(rgbBlue.getValue(), 100, 1);
  EXPECT_NEAR(rgbPurple.getValue(), 100, 1);
  EXPECT_NEAR(rgbRandom1.getValue(), 56, 1);
  EXPECT_NEAR(rgbRandom2.getValue(), 63, 1);
  EXPECT_NEAR(rgbRandom3.getValue(), 96, 1);
  EXPECT_NEAR(rgbRandom4.getValue(), 91, 1);
  EXPECT_NEAR(rgbRandom5.getValue(), 49, 1);
  EXPECT_NEAR(rgbRandom6.getValue(), 100, 1);
  EXPECT_NEAR(rgbRandom7.getValue(), 61, 1);
  EXPECT_NEAR(rgbRandom8.getValue(), 96, 1);
  EXPECT_NEAR(rgbRandom9.getValue(), 100, 1);
  EXPECT_NEAR(rgbRandom10.getValue(), 90, 1);

  //  EXPECT_NEAR(hexBlack.getValue(),  0   ,  1);
  //  EXPECT_NEAR(hexWhite.getValue(),  100 ,  1);
  //  EXPECT_NEAR(hexRed.getValue(),    100 ,  1);
  //  EXPECT_NEAR(hexYellow.getValue(), 100 ,  1);
  //  EXPECT_NEAR(hexGreen.getValue(),  100 ,  1);
  //  EXPECT_NEAR(hexCyan.getValue(),   100 ,  1);
  //  EXPECT_NEAR(hexBlue.getValue(),   100 ,  1);
  //  EXPECT_NEAR(hexPurple.getValue(), 100 ,  1);
  //  EXPECT_NEAR(hexRandom1.getValue(),56  ,  1);
  //  EXPECT_NEAR(hexRandom2.getValue(),63  ,  1);
  //  EXPECT_NEAR(hexRandom3.getValue(),96  ,  1);
  //  EXPECT_NEAR(hexRandom4.getValue(),91  ,  1);
  //  EXPECT_NEAR(hexRandom5.getValue(),49  ,  1);
  //  EXPECT_NEAR(hexRandom6.getValue(),100 ,  1);
  //  EXPECT_NEAR(hexRandom7.getValue(),61  ,  1);
  //  EXPECT_NEAR(hexRandom8.getValue(),96  ,  1);
  //  EXPECT_NEAR(hexRandom9.getValue(),100 ,  1);
  //  EXPECT_NEAR(hexRandom10.getValue(),90 ,  1);

  EXPECT_NEAR(hslBlack.getValue(), 0, 1);
  EXPECT_NEAR(hslWhite.getValue(), 100, 1);
  EXPECT_NEAR(hslRed.getValue(), 100, 1);
  EXPECT_NEAR(hslYellow.getValue(), 100, 1);
  EXPECT_NEAR(hslGreen.getValue(), 100, 1);
  EXPECT_NEAR(hslCyan.getValue(), 100, 1);
  EXPECT_NEAR(hslBlue.getValue(), 100, 1);
  EXPECT_NEAR(hslPurple.getValue(), 100, 1);
  EXPECT_NEAR(hslRandom1.getValue(), 56, 1);
  EXPECT_NEAR(hslRandom2.getValue(), 63, 1);
  EXPECT_NEAR(hslRandom3.getValue(), 96, 1);
  EXPECT_NEAR(hslRandom4.getValue(), 91, 1);
  EXPECT_NEAR(hslRandom5.getValue(), 49, 1);
  EXPECT_NEAR(hslRandom6.getValue(), 100, 1);
  EXPECT_NEAR(hslRandom7.getValue(), 61, 1);
  EXPECT_NEAR(hslRandom8.getValue(), 96, 1);
  EXPECT_NEAR(hslRandom9.getValue(), 100, 1);
  EXPECT_NEAR(hslRandom10.getValue(), 90, 1);

  EXPECT_NEAR(hsvBlack.getValue(), 0, 1);
  EXPECT_NEAR(hsvWhite.getValue(), 100, 1);
  EXPECT_NEAR(hsvRed.getValue(), 100, 1);
  EXPECT_NEAR(hsvYellow.getValue(), 100, 1);
  EXPECT_NEAR(hsvGreen.getValue(), 100, 1);
  EXPECT_NEAR(hsvCyan.getValue(), 100, 1);
  EXPECT_NEAR(hsvBlue.getValue(), 100, 1);
  EXPECT_NEAR(hsvPurple.getValue(), 100, 1);
  EXPECT_NEAR(hsvRandom1.getValue(), 56, 1);
  EXPECT_NEAR(hsvRandom2.getValue(), 63, 1);
  EXPECT_NEAR(hsvRandom3.getValue(), 96, 1);
  EXPECT_NEAR(hsvRandom4.getValue(), 91, 1);
  EXPECT_NEAR(hsvRandom5.getValue(), 49, 1);
  EXPECT_NEAR(hsvRandom6.getValue(), 100, 1);
  EXPECT_NEAR(hsvRandom7.getValue(), 61, 1);
  EXPECT_NEAR(hsvRandom8.getValue(), 96, 1);
  EXPECT_NEAR(hsvRandom9.getValue(), 100, 1);
  EXPECT_NEAR(hsvRandom10.getValue(), 90, 1);
}

TEST_F(ColorTest, GetLightness) {
  EXPECT_NEAR(rgbBlack.getLightness(), 0, 1);
  EXPECT_NEAR(rgbWhite.getLightness(), 100, 1);
  EXPECT_NEAR(rgbRed.getLightness(), 50, 1);
  EXPECT_NEAR(rgbYellow.getLightness(), 50, 1);
  EXPECT_NEAR(rgbGreen.getLightness(), 50, 1);
  EXPECT_NEAR(rgbCyan.getLightness(), 50, 1);
  EXPECT_NEAR(rgbBlue.getLightness(), 50, 1);
  EXPECT_NEAR(rgbPurple.getLightness(), 50, 1);
  EXPECT_NEAR(rgbRandom1.getLightness(), 39, 1);
  EXPECT_NEAR(rgbRandom2.getLightness(), 51, 1);
  EXPECT_NEAR(rgbRandom3.getLightness(), 76, 1);
  EXPECT_NEAR(rgbRandom4.getLightness(), 68, 1);
  EXPECT_NEAR(rgbRandom5.getLightness(), 30, 1);
  EXPECT_NEAR(rgbRandom6.getLightness(), 65, 1);
  EXPECT_NEAR(rgbRandom7.getLightness(), 54, 1);
  EXPECT_NEAR(rgbRandom8.getLightness(), 86, 1);
  EXPECT_NEAR(rgbRandom9.getLightness(), 62.4, 1);
  EXPECT_NEAR(rgbRandom10.getLightness(), 51, 1);

  //  EXPECT_NEAR(hexBlack.getLightness(),   0     ,1);
  //  EXPECT_NEAR(hexWhite.getLightness(),   100   ,1);
  //  EXPECT_NEAR(hexRed.getLightness(),     50    ,1);
  //  EXPECT_NEAR(hexYellow.getLightness(),  50    ,1);
  //  EXPECT_NEAR(hexGreen.getLightness(),   50    ,1);
  //  EXPECT_NEAR(hexCyan.getLightness(),    50    ,1);
  //  EXPECT_NEAR(hexBlue.getLightness(),    50    ,1);
  //  EXPECT_NEAR(hexPurple.getLightness(),  50    ,1);
  //  EXPECT_NEAR(hexRandom1.getLightness(), 39    ,1);
  //  EXPECT_NEAR(hexRandom2.getLightness(), 51    ,1);
  //  EXPECT_NEAR(hexRandom3.getLightness(), 76    ,1);
  //  EXPECT_NEAR(hexRandom4.getLightness(), 68    ,1);
  //  EXPECT_NEAR(hexRandom5.getLightness(), 30    ,1);
  //  EXPECT_NEAR(hexRandom6.getLightness(), 65    ,1);
  //  EXPECT_NEAR(hexRandom7.getLightness(), 54    ,1);
  //  EXPECT_NEAR(hexRandom8.getLightness(), 86    ,1);
  //  EXPECT_NEAR(hexRandom9.getLightness(), 62.4  ,1);
  //  EXPECT_NEAR(hexRandom10.getLightness(),51    ,1);

  EXPECT_NEAR(hslBlack.getLightness(), 0, 1);
  EXPECT_NEAR(hslWhite.getLightness(), 100, 1);
  EXPECT_NEAR(hslRed.getLightness(), 50, 1);
  EXPECT_NEAR(hslYellow.getLightness(), 50, 1);
  EXPECT_NEAR(hslGreen.getLightness(), 50, 1);
  EXPECT_NEAR(hslCyan.getLightness(), 50, 1);
  EXPECT_NEAR(hslBlue.getLightness(), 50, 1);
  EXPECT_NEAR(hslPurple.getLightness(), 50, 1);
  EXPECT_NEAR(hslRandom1.getLightness(), 39, 1);
  EXPECT_NEAR(hslRandom2.getLightness(), 51, 1);
  EXPECT_NEAR(hslRandom3.getLightness(), 76, 1);
  EXPECT_NEAR(hslRandom4.getLightness(), 68, 1);
  EXPECT_NEAR(hslRandom5.getLightness(), 30, 1);
  EXPECT_NEAR(hslRandom6.getLightness(), 65, 1);
  EXPECT_NEAR(hslRandom7.getLightness(), 54, 1);
  EXPECT_NEAR(hslRandom8.getLightness(), 86, 1);
  EXPECT_NEAR(hslRandom9.getLightness(), 62.4, 1);
  EXPECT_NEAR(hslRandom10.getLightness(), 51, 1);

  EXPECT_NEAR(hsvBlack.getLightness(), 0, 1);
  EXPECT_NEAR(hsvWhite.getLightness(), 100, 1);
  EXPECT_NEAR(hsvRed.getLightness(), 50, 1);
  EXPECT_NEAR(hsvYellow.getLightness(), 50, 1);
  EXPECT_NEAR(hsvGreen.getLightness(), 50, 1);
  EXPECT_NEAR(hsvCyan.getLightness(), 50, 1);
  EXPECT_NEAR(hsvBlue.getLightness(), 50, 1);
  EXPECT_NEAR(hsvPurple.getLightness(), 50, 1);
  EXPECT_NEAR(hsvRandom1.getLightness(), 39, 1);
  EXPECT_NEAR(hsvRandom2.getLightness(), 51, 1);
  EXPECT_NEAR(hsvRandom3.getLightness(), 76, 1);
  EXPECT_NEAR(hsvRandom4.getLightness(), 68, 1);
  EXPECT_NEAR(hsvRandom5.getLightness(), 30, 1);
  EXPECT_NEAR(hsvRandom6.getLightness(), 65, 1);
  EXPECT_NEAR(hsvRandom7.getLightness(), 54, 1);
  EXPECT_NEAR(hsvRandom8.getLightness(), 86, 1);
  EXPECT_NEAR(hsvRandom9.getLightness(), 62.4, 1);
  EXPECT_NEAR(hsvRandom10.getLightness(), 51, 1);
}

int main(int argc, char **argv) {
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
